version: '3.9'

services:
  postgres:
    container_name: invest-bank-postgres
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: invest-bank
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invest-bank-db
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local